name: build-package

on: 
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Create a release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Build package
        env:
          VERSION_TAG: ${{ github.ref }}
        run: |
          make
      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.ref }}"
          prerelease: false
          title: "Build ${{ github.ref }}"
          files: |
            build/kdeplasma-applets-batterybar.plasmoid
            build/PKGBUILD
