name: build-package

on: 
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Create a release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Build package
        env:
          VERSION_TAG: ${{ github.ref }}
        run: |
          env VERSION=$(echo ${VERSION_TAG} | cut -c2-)
          make
      - name: Create Release
        id: create_release
        uses: marvinpinto/action-automatic-releases@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ github.ref }}
          prerelease: false
          title: "Release ${{ github.ref }}"
          files: |
            build/kdeplasma-applets-batterybar.plasmoid
            build/PKGBUILD
