name: build-package

on: 
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Create a release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Get version tag
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Build package
        env:
          VERSION_TAG: ${{ github.ref }}
        run: |
          make
      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.ref }}"
          prerelease: false
          title: "Build ${{ steps.get_version.outputs.VERSION }}"
          files: |
            build/org.kde.batteryBar.plasmoid
            build/PKGBUILD
